baseurl = "/"
title = "ivrios"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

googleAnalytics = "UA-123456"

[params]
tagline = "We're launching a new, better solution."
helloemail = "mailto:hello@ivrios.com"
hellotext = "hello@ivrios.com"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]